--- org.apache.qpid.jms.integration.ConsumerIntegrationTest::testConsumerReceiveThrowsIfConnectionLost
junit.framework.AssertionFailedError: An exception should have been thrown
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.qpid.jms.integration.ConsumerIntegrationTest.doConsumerReceiveThrowsIfConnectionLostTestImpl(ConsumerIntegrationTest.java:322)
	at org.apache.qpid.jms.integration.ConsumerIntegrationTest.testConsumerReceiveThrowsIfConnectionLost(ConsumerIntegrationTest.java:276)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
